# Generated by Django 4.1.2 on 2022-10-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="scientific_name",
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
